# Config file for Car Dataset

output_dir: './checkpoints/ckp_car_512'
structure: 'linear'
device_id: ('1')
checkpoint_factor: 40
dataset:
  img_dir: '../data/car'
  folder: False
  resolution: 512
sched:
  # 4,8,16,32,64,128,256,512
  epochs: [40,80,80,80,80,120,120,160]